name: test-app-actions
run-name: Test app install with app-action

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "Target runner"
        required: true
        type: string
        default: "ubuntu-latest"
      arch:
        description: "Target architecture (e.g., arm64, amd64)"
        required: true
        type: string
        default: "amd64"
  workflow_call:
    inputs:
      runs-on:
        description: "Target runner"
        required: true
        type: string
        default: "ubuntu-latest"
      arch:
        description: "Target architecture (e.g., arm64, amd64)"
        required: true
        type: string
        default: "amd64"

jobs:
  test-app-actions:
    runs-on: ${{ inputs.runs-on }}${{ inputs.arch == 'arm64' && '-arm' || '' }}

    steps:
      - name: Enable linger and create user session (workaround)
        uses: gbraad-actions/blacksmith-user-session@main

      - name: Allow unprivileged userns (workaround)
        uses: gbraad-actions/warpbuild-unprivileged-userns@main

      - name: Setup environment
        uses: gbraad-dotfiles/install-action@main
        with:
          upstream: true

      - name: Run app command - install code
        uses: gbraad-dotfiles/app-action@main
        with:
          appname: code
          action: install

      - name: Run app command - install codium
        uses: gbraad-dotfiles/app-action@main
        with:
          appname: codium
          action: install

      - name: Run app command - install codium-server
        uses: gbraad-dotfiles/app-action@main
        with:
          appname: codium-server
          action: install

      - name: Run app command - install clion
        uses: gbraad-dotfiles/app-action@main
        with: 
          appname: clion
          action: install

      - name: Run app command - install obsidian
        uses: gbraad-dotfiles/app-action@main
        with: 
          appname: obsidian
          action: install
          args: user

      - name: Run app command - install vivaldi
        uses: gbraad-dotfiles/app-action@main
        with: 
          appname: vivaldi
          action: install
